#!/usr/bin/env bash
# Sync V-Team resource definitions into a product repo.
#
#   ./scripts/sync.sh ../prism-platform            # copy in
#   ./scripts/sync.sh ../prism-platform --check    # fail on drift, copy nothing
#
# This repo is the source of truth. A product's .claude/agents/ is a mirror —
# never edit it there; edit here and re-sync.
#
# NOTHING RUNS --check AUTOMATICALLY. This header used to claim it "mirrors the
# CLAUDE.md/AGENTS.md drift check prism-platform already runs"; it does not.
# prism-platform's agents-sync workflow compares CLAUDE.md to AGENTS.md and
# never looks at .claude/agents/, which is not even tracked there. On
# 2026-08-16 all eight mirrored files were found stale by half a day, missing a
# whole section. Until a CI job in the product repo runs
# `sync.sh <repo> --check`, mirror freshness is a habit, not a guard — see
# ledger/gaps/2026-08-16-callsign-not-on-the-dispatch-surface.md.

set -euo pipefail

TARGET="${1:-}"
MODE="${2:-write}"
SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/resources"

if [[ -z "$TARGET" ]]; then
  echo "usage: $0 <path-to-product-repo> [--check]" >&2
  exit 2
fi

if [[ ! -d "$TARGET/.git" ]]; then
  echo "error: $TARGET is not a git repository" >&2
  exit 2
fi

DEST="$TARGET/.claude/agents"

if [[ "$MODE" == "--check" ]]; then
  status=0
  for f in "$SRC"/*.md; do
    name="$(basename "$f")"
    if [[ ! -f "$DEST/$name" ]]; then
      echo "::error::missing in $TARGET: .claude/agents/$name"
      status=1
    elif ! diff -q "$f" "$DEST/$name" >/dev/null; then
      echo "::error::drifted: .claude/agents/$name — re-run sync.sh from v-team"
      diff -u "$f" "$DEST/$name" || true
      status=1
    fi
  done
  [[ $status -eq 0 ]] && echo "in sync: $TARGET"
  exit $status
fi

mkdir -p "$DEST"
cp "$SRC"/*.md "$DEST/"

# The ACTIVE callsign roster, for guards in the product repo.
#
# A product repo has no registry.yaml, so `check-attribution.sh` had no way to
# ask whether a co-author names a real resource — it validated trailer SHAPE
# and passed `Co-authored-by: Neo <neo@indianvcs.com>` on five commits, Neo
# having been retired the previous day for failing the species test. A retired
# callsign in a merged trailer is permanent and unresolvable.
#
# One callsign per line, uppercase-first exactly as registry.yaml spells it.
# TRACK THIS FILE. A guard that reads a missing roster must FAIL, never pass —
# see ledger/escapes/2026-08-16-retired-callsign-passed-the-guard.md.
#
# THREE STATES, not two. A plain membership check would start failing on
# legitimate history the moment anyone is retired — and six were retired on
# 2026-08-16 — so `retired` is a first-class row, not an absence:
#
#   active   <callsign>  <resource>   passes
#   retired  <callsign>  <resource>   passes, resolves to the resource, note it
#   (absent)                          FAILS — an unknown callsign credits nobody
#
ROSTER="$TARGET/.v-team-callsigns"
REG="$(dirname "$SRC")/registry.yaml"
{
  echo "# V-Team callsigns — generated by v-team scripts/sync.sh. Do not edit."
  echo "# <state>\t<callsign>\t<resource-id>"
  echo "# A Co-authored-by trailer naming a callsign absent from this file is"
  echo "# misattributed and must FAIL. A 'retired' one is legitimate history."
  # Callsign lives on people: now (docs/org-model.md, stage 1+2), one row per
  # role today — block-scoped so retired_callsigns' identical "  - callsign: "
  # shape can never leak into the active list.
  awk '
    /^people:/         { inb=1; next }
    /^[a-z_]+:/        { inb=0 }
    inb && /^  - callsign: / { c=$0; sub(/^  - callsign: /,"",c); sub(/[[:space:]]*#.*/,"",c); gsub(/[[:space:]]*$/,"",c) }
    inb && /^    role: /     { r=$0; sub(/^    role: /,"",r); sub(/[[:space:]]*#.*/,"",r); gsub(/[[:space:]]*$/,"",r)
                               if (c != "") { print "active\t" c "\t" r; c="" } }
  ' "$REG"
  awk '
    /^retired_callsigns:/ { inblock=1; next }
    /^[a-z_]+:/           { inblock=0 }
    inblock && /^  - callsign: / { c=$0; sub(/^  - callsign: /,"",c); gsub(/[[:space:]]/,"",c) }
    inblock && /^    resource: /  { r=$0; sub(/^    resource: /,"",r); gsub(/[[:space:]]/,"",r)
                                    if (c != "") { print "retired\t" c "\t" r; c="" } }
  ' "$REG"
} > "$ROSTER"

echo "synced $(ls -1 "$SRC"/*.md | wc -l | tr -d ' ') resources -> $DEST"
echo "wrote $(grep -c '^active' "$ROSTER") active + $(grep -c '^retired' "$ROSTER") retired callsigns -> $ROSTER"
echo "commit them in $TARGET on a branch — never straight to master."
